import Head from "next/head";
import styles from "../styles/Home.module.css";
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
// import { health } from "../assets/health.jpg";

export default function Home() {
  const responsive = {
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3,
      slidesToSlide: 3, // optional, default to 1.
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
      slidesToSlide: 2, // optional, default to 1.
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
      slidesToSlide: 1, // optional, default to 1.
    },
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel
        swipeable={false}
        draggable={false}
        showDots={true}
        responsive={responsive}
        ssr={true} // means to render carousel on server-side.
        infinite={true}
        // autoPlay={this.props.deviceType !== "mobile" ? true : false}
        autoPlaySpeed={1000}
        keyBoardControl={true}
        customTransition="all .5"
        transitionDuration={500}
        containerClass="carousel-container"
        removeArrowOnDeviceType={["tablet", "mobile"]}
        // deviceType={this.props.deviceType}
        dotListClass="custom-dot-list-style"
        itemClass="carousel-item-padding-40-px"
      >
        <div>
          <img
            src="https://oushodsheba.com/_next/static/images/Health_care_products-60163f671ce25ab0d622e6cd7b622f83.jpg"
            alt="hello"
          />
        </div>
        <div>
          <img
            src="https://oushodsheba.com/_next/static/images/gp_banner-b5aa753fbfeee5776f8c2f780bf7b35f.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://oushodsheba.com/_next/static/images/Health_care_products-60163f671ce25ab0d622e6cd7b622f83.jpg"
            alt=""
          />
        </div>
        <div>
          <img
            src="https://oushodsheba.com/_next/static/images/gp_banner-b5aa753fbfeee5776f8c2f780bf7b35f.jpg"
            alt=""
          />
        </div>
      </Carousel>
    </div>
  );
}
